# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mpay',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('alipay', models.IntegerField()),
                ('wxpay', models.IntegerField()),
                ('ccb', models.IntegerField()),
                ('succee', models.IntegerField()),
                ('fail', models.IntegerField()),
                ('ip_time', models.DateField()),
            ],
        ),
    ]
